added: added subnet input only

diff --git a/IPv4Calculator b/IPv4Calculator
--- a/IPv4Calculator
+++ b/IPv4Calculator
@@ -8,8 +8,22 @@
 #check if they have bc installed if not return please isntall bc and tell them the command
 
 #is awk downloaded?
+bruh=( $1 )
+if [[ ! -n $1 ]]; then
+	echo "your argument passed is not a string"
+	exit 1
+fi
 
-stringwithDotslash="10.30.4.19/18"
+#actually a scary crazy regular expression
+formatted='^((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.){3}((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]?[0-9]))/(3[0-2]|[1-2]?[0-9])$'
+
+if [[ ! $bruh =~ $formatted ]]; then
+	echo "Error: your input does not match that of an IPv4 address 
+example = 10.20.30.40/20"
+	exit 1
+fi
+
+stringwithDotslash="$bruh"
 
 spacedString=${stringwithDotslash//./ }
 #removed slash from subnet not array
